export const OUTPUT_FORMATS = Object.freeze(['redacted-json', 'json', 'netscape', 'cookie-header', 'set-cookie', 'curl']);

export function serializeCookies(cookies, options = {}) {
  const format = options.format ?? 'redacted-json';
  if (!OUTPUT_FORMATS.includes(format)) throw new Error(`Unsupported output format: ${format}`);
  const filtered = options.includeHttpOnly ? [...cookies] : cookies.filter((cookie) => !cookie.httpOnly);
  switch (format) {
    case 'redacted-json': return serializeJson(filtered, true, options.pretty !== false);
    case 'json': return serializeJson(filtered, false, options.pretty !== false);
    case 'netscape': return serializeNetscape(filtered);
    case 'cookie-header': return serializeHeader(filtered);
    case 'set-cookie': return serializeSetCookie(filtered);
    case 'curl': return serializeCurl(filtered, options.hostname ?? 'example.invalid');
    default: throw new Error(`Unhandled format: ${format}`);
  }
}

export function serializeJson(cookies, redacted = false, pretty = true) {
  const records = cookies.map((cookie) => ({
    name: cookie.name,
    value: redacted ? '[REDACTED]' : cookie.value,
    domain: cookie.domain,
    path: cookie.path,
    secure: cookie.secure,
    httpOnly: cookie.httpOnly,
    sameSite: cookie.sameSite,
    expirationDate: cookie.expirationDate ?? null,
    session: cookie.session,
    hostOnly: cookie.hostOnly,
    storeId: cookie.storeId ?? null,
    metadata: cookie.metadata,
  }));
  return JSON.stringify(records, null, pretty ? 2 : 0);
}

export function serializeNetscape(cookies) {
  const lines = [
    '# Netscape HTTP Cookie File',
    '# Generated by Luck Editor Web Lab',
    '# Review cookie values before sharing.',
    '',
  ];
  for (const cookie of cookies) {
    const domain = `${cookie.httpOnly ? '#HttpOnly_' : ''}${cookie.domain}`;
    lines.push([
      sanitizeField(domain),
      cookie.domain.startsWith('.') ? 'TRUE' : 'FALSE',
      sanitizeField(cookie.path || '/'),
      cookie.secure ? 'TRUE' : 'FALSE',
      String(Math.floor(cookie.expirationDate ?? 0)),
      sanitizeField(cookie.name),
      sanitizeField(cookie.value),
    ].join('\t'));
  }
  return `${lines.join('\n')}\n`;
}

export function serializeHeader(cookies) {
  return `Cookie: ${cookies.map((cookie) => `${cookie.name}=${sanitizeHeaderValue(cookie.value)}`).join('; ')}`;
}

export function serializeSetCookie(cookies) {
  return cookies.map((cookie) => {
    const attributes = [`Path=${sanitizeAttribute(cookie.path || '/')}`];
    if (cookie.domain.startsWith('.')) attributes.push(`Domain=${sanitizeAttribute(cookie.domain)}`);
    if (cookie.expirationDate) attributes.push(`Expires=${new Date(cookie.expirationDate * 1000).toUTCString()}`);
    if (cookie.secure) attributes.push('Secure');
    if (cookie.httpOnly) attributes.push('HttpOnly');
    if (cookie.sameSite !== 'unspecified') {
      const sameSite = cookie.sameSite === 'no_restriction' ? 'None' : title(cookie.sameSite);
      attributes.push(`SameSite=${sameSite}`);
    }
    if (cookie.metadata.partitioned === 'true') attributes.push('Partitioned');
    if (cookie.metadata.priority) attributes.push(`Priority=${sanitizeAttribute(cookie.metadata.priority)}`);
    return `Set-Cookie: ${cookie.name}=${sanitizeHeaderValue(cookie.value)}; ${attributes.join('; ')}`;
  }).join('\n');
}

export function serializeCurl(cookies, hostname) {
  const host = String(hostname).trim().replace(/^https?:\/\//i, '').replace(/\/+$/, '') || 'example.invalid';
  const header = cookies.map((cookie) => `${cookie.name}=${cookie.value}`).join('; ');
  return `curl --fail --show-error --location --cookie ${shellQuote(header)} ${shellQuote(`https://${host}/`)}`;
}

export function downloadText(filename, content) {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = safeFilename(filename);
  anchor.click();
  window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function safeFilename(value) {
  const normalized = String(value).normalize('NFKD').replace(/[^A-Za-z0-9._-]+/g, '_').replace(/^_+|_+$/g, '');
  return (normalized || 'luck-editor-export.txt').slice(0, 120);
}

function sanitizeField(value) {
  return String(value).replace(/[\t\r\n]/g, ' ');
}

function sanitizeHeaderValue(value) {
  return String(value).replace(/[\r\n;]/g, '');
}

function sanitizeAttribute(value) {
  return String(value).replace(/[\r\n;]/g, '');
}

function shellQuote(value) {
  return `'${String(value).replaceAll("'", `'"'"'`)}'`;
}

function title(value) {
  return value.charAt(0).toUpperCase() + value.slice(1).toLowerCase();
}
