use crate::error::Result;
use crate::model::CookieCollection;
use std::fmt::Write;

pub(super) fn serialize(collection: &CookieCollection) -> Result<String> {
    let mut output = String::from("# Netscape HTTP Cookie File\n# Generated by Luck Editor 5\n# Review exported secrets before sharing.\n\n");
    for cookie in collection {
        let domain = if cookie.http_only { format!("#HttpOnly_{}", cookie.domain) } else { cookie.domain.clone() };
        let include_subdomains = if cookie.domain.starts_with('.') { "TRUE" } else { "FALSE" };
        let secure = if cookie.secure { "TRUE" } else { "FALSE" };
        let expiry = cookie.expiration_date.unwrap_or_default().floor() as i64;
        writeln!(
            output,
            "{}\t{}\t{}\t{}\t{}\t{}\t{}",
            domain,
            include_subdomains,
            cookie.path,
            secure,
            expiry,
            sanitize_field(&cookie.name),
            sanitize_field(&cookie.value)
        )
        .map_err(|error| crate::error::LuckError::Serialization(error.to_string()))?;
    }
    Ok(output)
}

fn sanitize_field(value: &str) -> String {
    value.replace(['\t', '\r', '\n'], " ")
}
