import { APP_NAME, APP_VERSION } from '../core/constants.js';
import { assertNever } from '../core/errors.js';
import { safeNavigationUrl } from '../core/url.js';
import type { CookieRecord, ExportFormat } from '../core/types.js';

export interface SerializeOptions {
  readonly format: ExportFormat;
  readonly hostname: string;
  readonly includeHttpOnly: boolean;
}

export function serializeCookies(cookies: readonly CookieRecord[], options: SerializeOptions): string {
  const filtered = options.includeHttpOnly ? cookies : cookies.filter((cookie) => !cookie.httpOnly);
  switch (options.format) {
    case 'json': return serializeJson(filtered, false);
    case 'redacted-json': return serializeJson(filtered, true);
    case 'netscape': return serializeNetscape(filtered);
    case 'cookie-header': return serializeHeader(filtered);
    case 'set-cookie': return serializeSetCookie(filtered);
    case 'curl': return serializeCurl(filtered, options.hostname);
    default: return assertNever(options.format);
  }
}

function serializeJson(cookies: readonly CookieRecord[], redact: boolean): string {
  return JSON.stringify(cookies.map((cookie) => ({
    name: cookie.name,
    value: redact ? '[REDACTED]' : cookie.value,
    domain: cookie.domain,
    path: cookie.path,
    secure: cookie.secure,
    httpOnly: cookie.httpOnly,
    sameSite: cookie.sameSite,
    expirationDate: cookie.expirationDate ?? null,
    session: !cookie.expirationDate,
    storeId: cookie.storeId,
  })), null, 2);
}

function serializeNetscape(cookies: readonly CookieRecord[]): string {
  const lines = [`# Netscape HTTP Cookie File`, `# Generated by ${APP_NAME} ${APP_VERSION}`, '# Review exported secrets before sharing.', ''];
  for (const cookie of cookies) {
    const domain = `${cookie.httpOnly ? '#HttpOnly_' : ''}${cookie.domain}`;
    const includeSubdomains = cookie.domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const secure = cookie.secure ? 'TRUE' : 'FALSE';
    const expiry = Math.floor(cookie.expirationDate ?? 0);
    lines.push([domain, includeSubdomains, cookie.path || '/', secure, String(expiry), cookie.name, cookie.value].join('\t'));
  }
  return `${lines.join('\n')}\n`;
}

function serializeHeader(cookies: readonly CookieRecord[]): string {
  return `Cookie: ${cookies.map((cookie) => `${cookie.name}=${cookie.value}`).join('; ')}`;
}

function serializeSetCookie(cookies: readonly CookieRecord[]): string {
  return cookies.map((cookie) => {
    const attributes = [`Path=${cookie.path || '/'}`];
    if (cookie.domain.startsWith('.')) attributes.push(`Domain=${cookie.domain}`);
    if (cookie.expirationDate) attributes.push(`Expires=${new Date(cookie.expirationDate * 1000).toUTCString()}`);
    if (cookie.secure) attributes.push('Secure');
    if (cookie.httpOnly) attributes.push('HttpOnly');
    if (cookie.sameSite !== 'unspecified') attributes.push(`SameSite=${cookie.sameSite === 'no_restriction' ? 'None' : title(cookie.sameSite)}`);
    return `Set-Cookie: ${cookie.name}=${cookie.value}; ${attributes.join('; ')}`;
  }).join('\n');
}

function serializeCurl(cookies: readonly CookieRecord[], hostname: string): string {
  const cookieText = cookies.map((cookie) => `${cookie.name}=${cookie.value}`).join('; ').replace(/'/g, `'"'"'`);
  return `curl --fail --show-error --location --cookie '${cookieText}' '${safeNavigationUrl(hostname)}'`;
}

function title(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1).toLowerCase();
}
